Vue 2.0 support
CroudSupport/vue-semantic pull request #8
Opened 2016-10-05 14:08 UTC by aphofstede

2016-11-02 14:49 UTC, aambrozkiewicz commented
this seems very nice, what stops it from being merged?

2016-11-17 11:54 UTC, BrockReece commented
Hi,

Sorry for the slow reply, github didn't notify me about this PR.
I am happy to merge in these changes but don't want to break anything for anyone still using Vue 1. 

Do you think I should merge these changes into a new branch and then the users can choose the version they need?

Cheers
Brock

2016-11-19 10:22 UTC, aphofstede commented
I would tag & branch the current master as the last 1.x and continue on master with 2.0. Anyone depending directly on a head should expect breaking changes right?

-- 
Alexander Hofstede

> On 17 Nov 2016, at 18:54, BrockReece <notifications@github.com> wrote:
> 
> Hi,
> 
> Sorry for the slow reply, github didn't notify me about this PR.
> I am happy to merge in these changes but don't want to break anything for anyone still using Vue 1.
> 
> Do you think I should merge these changes into a new branch and then the users can choose the version they need?
> 
> Cheers
> Brock
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
>

2017-01-28 08:40 UTC, OmgImAlexis requested changes

2017-01-28 08:40 UTC, OmgImAlexis commented on src/Dropdown.vue
> +    <input type="hidden" v-bind:name="name" value="{{selection}}">
This should be `v-bind:value="selection"`

2017-03-14 20:09 UTC, ricardovf commented
@BrockReece wont this be merged?

2017-03-22 16:53 UTC, BrockReece commented
@ricardovf 

I found a few issues with this PR when trying it in anger in my own applications so I am using this as a starting point and fixing the little niggles as I go, I should have this up by the end of the week.

Sorry for the delay again
Brock

2019-05-15 13:01 UTC, closed without merging